server:
  port: ${GATEWAY_PORT:8088}

spring:
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: product-service-route
          uri: lb://product-service
          predicates:
            - Path=/api/products/**,/internal/products/**
        - id: order-service-route
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**,/api/test/**,/api/config/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always
