server.port=8080
management.endpoints.web.exposure.include=health,info,env,refresh
management.endpoint.health.show-details=always

spring.datasource.url=jdbc:mysql://mysql:3306/seckill_system?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis.configuration.map-underscore-to-camel-case=true

instance.id=${INSTANCE_ID:docker}

spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms

spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=seckill-order-group
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.cloud.compatibility-verifier.enabled=false
spring.cloud.sentinel.transport.dashboard=${SENTINEL_DASHBOARD:sentinel-dashboard:8858}
spring.cloud.sentinel.eager=true
spring.cloud.sentinel.web-context-unify=false

seckill.kafka.order-create-topic=seckill-order-create-topic
seckill.kafka.inventory-deduct-topic=seckill-inventory-deduct-topic
seckill.kafka.inventory-result-topic=seckill-inventory-result-topic
seckill.kafka.payment-topic=seckill-payment-topic
seckill.kafka.payment-result-topic=seckill-payment-result-topic
seckill.redis.stock-prefix=seckill:stock:
seckill.redis.user-order-prefix=seckill:order:user:
seckill.id.worker-id=1
seckill.id.datacenter-id=1
seckill.demo.message=hello-from-docker-config
seckill.demo.gateway-prefix=/seckill
seckill.sentinel.hotspot-qps=2
seckill.sentinel.order-qps=10
seckill.sentinel.degrade-threshold-ms=300
